### PR TITLE
Improve importing scores via json

### PR DESCRIPTION
**Pull request by wrac4242**
add information about the json formatting required to import scores

### CODE REVIEW

**Review by itzJOHv — CHANGES_REQUESTED** [review]
add a space after `20` so it won't look messed up

**Comment by wrac4242** [comment]
added space

**Review by itzJOHv — APPROVED** [review]
looks good

**Comment by promise** [comment]
commands get automatically documented with the autodoc.js script, this would just be overwritten next time.

this is also a very odd place to put it regardless. it would make more sense to have this information under the command's section of the document instead of in the table-of-contents of the document.

**Pull request closed without merging**
